### ISSUE TITLE
Decentralized vehicle registration protocol

### ISSUE THREAD

**Issue by lam3lka** [blockchain-IoT/blockchain-IoT-core#19]
Feature request

As a product owner
to deliver appropriate contracts for vehicle registration
I need to invent a trustless decentralized protocol
which involves only the motorcycle owner 
and involves storing cryptographic proof of the process
and does not involve any relay business
or other central authority

Suggestion
1. Try to depict the algorithm like a flow diagram
2. We can assume that the vehicle's registration documents and insurance are proofs that the motorcycle owner has the right vehicle disposal

**Comment by longersson** [comment]
#22 Is a proposed solution for this problem.

Problem aspects addressed:
- Vehicle owner/controller **identity** confirmation,
- Vehicle **ownership** and technical **condition** verification.

The algorithm we propose includes final verification carried out by the first renter. The first renter can be trusted on condition that that in his best interest lies to collect a fully functional and legal vehicle.

Our highlights:
First-renter verification will not be sufficient in some circumstances. In particular, it will fail in the case of existence of extra-systematic agreements between the leaser and the vehicle owner. Such agreements may be aimed at abusing the platform and need to be taken into consideration in expansion of the procedure.

Design team:
- Anna Frankowska (Nightset),
- Artur Karwatka (Gamention),
- Piotr Sobczak,
- Patryk Kocielnik
