### ISSUE TITLE
Communication design

### ISSUE THREAD

**Issue by michalmikolajczyk** [blockchain-IoT/blockchain-IoT-core#2]
The project needs some kind of visual communication (industrial?) design. In particular, we should discuss:

- the names for the project, and the repos
- the logo
- the visual language we will use throughout the app (I would suggest [Material Design](https://material.io/))

All suggestions welcome!

**Comment by michalmikolajczyk** [comment]
IMO, the name `blockchain IoT` is quite catchy, and it describes what we do at the same time :)

As for the visual language: Material Design is not the only one. I like minimalism, and the new trend, Type Design, kind of gets me :) Check out this article on Toptal blog, for an opinion on alternatives to Material Design: https://www.toptal.com/designers/ui/type-design

**Comment by BlueMan2017** [comment]
Material Design is past its prime, I think. Especially a year from now it will be;) This language, obviously, has its advantages like simplicity and familiarity. But for the IoT project, I propose fluent design (https://fluent.microsoft.com/) which assumes total immersion in a digital word. In context of IoT it can be a nice idea;)

**Comment by michalmikolajczyk** [comment]
@BlueMan2017 Fluent Design looks interesting! I think that m$ has quite a few good products for the open source community, like VS Code and TypeScript.

I could not find any major implementations yet though, and our main channel for communication will be HTML and CSS. The repos I found on Github are very early stage. Do you know any other resources or examples of implementation?

**Comment by michalmikolajczyk** [comment]
Over the past months, I did not see any new repos with fluent design show up.

I agree with @BlueMan2017 that Material Design is booring :) It is however familiar to many people, and that could be an advantage. The best React implementation is: https://material-ui-next.com/

I would recommend we go with Ant Design. It is an already mature, yet fresh design language, with a full ecosystem for React: https://ant.design/

As a third contender, I suggest Foundation https://foundation.zurb.com/

The decision will be made around the next meetup, planned at January 30

**Comment by BlueMan2017** [comment]
I agree - Microsoft has a problem with its "products implementations" recently ;) Furthermore, I don't remember any project that would be based directly on Fluent Design.
But... Material Design --> https://medium.com/techtrument/bye-bye-material-design-acaebcc7c6b4?ref=webdesignernews.com ;)
Ant looks nice, but a little bit... childish?
I haven't been looking for a better solution lately, I admit. So I have no right to judge your ideas. But I believe that a good design system is out there... ;)
P.S. Foundation is a framework, but you know that;p

**Comment by BlueMan2017** [comment]
https://adele.uxpin.com/?ref=webdesignernews.com

**Comment by michalmikolajczyk** [comment]
I gave it some thought and started developing with UI Kit https://getuikit.com/ it's ok, easy integration. You have a point there with Ant looking a bit immature. But UI Kit seems fine.

Insider's tip: we will host a workshop in Campus Warsaw on February 20. Come and join us :)
