### ISSUE TITLE
Add linting with eslint for Airbnb style guide 

### ISSUE THREAD

**Issue by michalmikolajczyk** [blockchain-IoT/blockchain-IoT-core#26]
As lead developer,
To achieve consistency and integrity across code
And avoid code smells
I request the addition of a linter like eslint https://eslint.org/docs/user-guide/configuring
And support for Airbnb style https://github.com/airbnb/javascript

**Comment by ganes1410** [comment]
I'll do this. @michalmikolajczyk

**Comment by michalmikolajczyk** [comment]
@ganes1410 #33 broke the project. There seem to be conflicting dependencies, and updates require major version changes of other packages incl. `webpack`.

Please submit a working eslint config. Basically `npm start` should compile and serve the project without errors.

**Comment by ganes1410** [comment]
my bad @michalmikolajczyk  .i will open a new pull request.

**Comment by ganes1410** [comment]
@michalmikolajczyk  i tried to add the linting.But because some of the npm packages are old.They are not compatible.And that's what broke the project.
