### ISSUE TITLE
Compare KYC and AML systems available on the market and choose the most suitable to integrate with our system

### ISSUE THREAD

**Issue by lam3lka** [blockchain-IoT/blockchain-IoT-core#34]
As a product owner
to deliver appropriate contracts for decentralized vehicle rentals
I need to authorize users
which is delegated to external KYC and AML system

**Comment by michalmikolajczyk** [comment]
This really is the concern of the business, and not the open-source library

**Comment by pbrudny** [comment]
Hey @michalmikolajczyk 
On Blockathon 2018 we formed a team to work on that issue. We have our solution based on PSD2 directive which let's us use banks API to do KYC. Here is the concept of that https://github.com/pbrudny/blockey The work is in progress. This month we will get Allior Bank support. If you are interested to cooperate we can stay in touch.
