### ISSUE TITLE
UIKit doesn't render spinners in React

### ISSUE THREAD

**Issue by ocet** [blockchain-IoT/blockchain-IoT-core#44]
### Expected behavior (user story)
I want to use `uk-spinner` inside JSX so that it renders properly.
### Actual behavior
`uk-spinner` is placed inside DOM with decorated element (i.e. `span` or `div`) but remains invisible (has 0px width).
### Steps to reproduce
Reproduced using either `uikit@3.0.0-beta.40` or `uikit@3.0.0-beta.22`
In JSX template, placing:
`<div className="uk-spinner"></div>`, 
`<div data-uk-spinner></div>`, or
`<span data-uk-spinner={''} />`
will not result in proper rendering.

This issue mimics:
https://github.com/uikit/uikit/issues/2663

Is falling back to UIKit@2.x.x an option?

**Comment by michalmikolajczyk** [comment]
nope, we should go with the new UIKit. spinners are not the most important, we can use different spinners. Like this stuff: http://www.davidhu.io/react-spinners/

Please create a new task if you want to add a spinner.
